### PR TITLE
Misc filter

### PR DESCRIPTION
**Pull request by steveoni**
This pull request adds some new update to the filter component as specified in #12 

Screen Shot 2021-03-11 at 10 00 46

### CODE REVIEW

**Comment by anuveyatsu** [comment]
@steveoni hey, could you please check how this is done on Energinet site because this implementation is not exactly what we need.

**Comment by steveoni** [comment]
@anuveyatsu the Energinet contains `month` field which is not available in this `graphql` api. I did this implementation like this, base on the `Hour DK` and `Hour UTC` fields

Screen Shot 2021-03-12 at 17 53 09

**Comment by anuveyatsu** [comment]
@steveoni ok, I got your confusion. Let me clarify:

- A field is described by a metadata. In this case, we're using frictionless tableschema - https://specs.frictionlessdata.io/table-schema/
- Based on that metadata, you should be able to figure out if a field contains date(time) data and display datepicker element.
- You shouldn't have logic based on field name as it can be anything.

**Comment by steveoni** [comment]
> @steveoni ok, I got your confusion. Let me clarify:
> 
> * A field is described by a metadata. In this case, we're using frictionless tableschema - https://specs.frictionlessdata.io/table-schema/
> * Based on that metadata, you should be able to figure out if a field contains date(time) data and display datepicker element.
> * You shouldn't have logic based on field name as it can be anything.
> 
> Also, note that you should be able to select range.

@anuveyatsu ok. now I understand what you mean. instead of checking if the field name is `HourDK` or `HourUTC`, I should check if the metadata of the field is datetime

**Comment by anuveyatsu** [comment]
@steveoni yes, it also can be just `date`

**Comment by steveoni** [comment]
@anuveyatsu here is the new update to the Date(time) field. You can filter by range and also by a single input  (same logic as energinet month filter field)


Screen Shot 2021-03-15 at 10 47 42

**Pull request merged**
